### PR TITLE
Add devise - Delivers #132282915

### PR DESCRIPTION
**Pull request by jeremyjpark**

### CODE REVIEW

**Review by LizzySteger — APPROVED** [review]
Looks good, allows signup/login

**Review by aganpule — COMMENTED** [review]
why does this not have sign up / sign in?

**Comment by jeremyjpark** [comment]
The sign up/in functionality is actually already in Iter2Staging; this PR is more an exercise in code review and workflow.

**Review by aganpule — APPROVED** [review]
looks good!

**Comment by jeremyjpark** [comment]
I'll be closing the pull request instead of merging as we already have it within Iter2Staging.

**Pull request closed without merging**
